name: devagram_flutter
description: Implementação do Devagram no flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  http: ^1.0.0
  mask_text_input_formatter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Biennale
      fonts:
        - asset: assets/fonts/BiennaleRegular.otf
        - asset: assets/fonts/BiennaleBold.otf
          weight: 600
        - asset: assets/fonts/BiennaleLight.otf
          weight: 400